<a href="https://colab.research.google.com/github/Sankari-Prem/Task-5/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv(r"/content/countries of the world.csv")

In [8]:
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [9]:
df = pd.read_table(r"/content/countries of the world.csv", sep = ',')
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [10]:
df = pd.read_json(r"/content/json_sample.json")
df

,12 Strong,A Fantastic Woman (Una Mujer FantÃ¡stica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,...,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...",...,"{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

In [12]:
df2 = pd.read_excel(r"/content/world_population_excel_workbook (1).xlsx", sheet_name = 'Sheet1')
df2

     Rank CCA3            Country           Capital
0      36  AFG        Afghanistan             Kabul
1     138  ALB            Albania            Tirana
2      34  DZA            Algeria           Algiers
3     213  ASM     American Samoa         Pago Pago
4     203  AND            Andorra  Andorra la Vella
..    ...  ...                ...               ...
229   226  WLF  Wallis and Futuna          Mata-Utu
230   172  ESH     Western Sahara         El AaiÃƒÂºn
231    46  YEM              Yemen             Sanaa
232    63  ZMB             Zambia            Lusaka
233    74  ZWE           Zimbabwe            Harare

[234 rows x 4 columns]

In [13]:
pd.set_option('display.max.rows', 235)
pd.set_option('display.max.columns', 40)

In [14]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     234 non-null    int64
 1   CCA3     234 non-null    object
 2   Country  234 non-null    object
 3   Capital  234 non-null    object
dtypes: int64(1), object(3)
memory usage: 7.4+ KB

In [15]:
df2.shape

(234, 4)

In [16]:
df2.head(10)

   Rank CCA3              Country           Capital
0    36  AFG          Afghanistan             Kabul
1   138  ALB              Albania            Tirana
2    34  DZA              Algeria           Algiers
3   213  ASM       American Samoa         Pago Pago
4   203  AND              Andorra  Andorra la Vella
5    42  AGO               Angola            Luanda
6   224  AIA             Anguilla        The Valley
7   201  ATG  Antigua and Barbuda    Saint JohnÃ¢â‚¬â„¢s
8    33  ARG            Argentina      Buenos Aires
9   140  ARM              Armenia           Yerevan

In [17]:
df2.tail(10)

     Rank CCA3            Country       Capital
224    43  UZB         Uzbekistan      Tashkent
225   181  VUT            Vanuatu     Port-Vila
226   234  VAT       Vatican City  Vatican City
227    51  VEN          Venezuela       Caracas
228    16  VNM            Vietnam         Hanoi
229   226  WLF  Wallis and Futuna      Mata-Utu
230   172  ESH     Western Sahara     El AaiÃƒÂºn
231    46  YEM              Yemen         Sanaa
232    63  ZMB             Zambia        Lusaka
233    74  ZWE           Zimbabwe        Harare

In [18]:
df2['Rank']

0       36
1      138
2       34
3      213
4      203
5       42
6      224
7      201
8       33
9      140
10     198
11      55
12      99
13      91
14     176
15     154
16       8
17     186
18      96
19      81
20     177
21      77
22     206
23     165
24      80
25     137
26     144
27       7
28     221
29     175
30     108
31      58
32      78
33      73
34      53
35      39
36     171
37     205
38     117
39      69
40      65
41       1
42      28
43     163
44     223
45     124
46     130
47      85
48     189
49     158
50      88
51     115
52     160
53     204
54      84
55      15
56      67
57      14
58     112
59     152
60     132
61     156
62     159
63      12
64     231
65     209
66     162
67     118
68      23
69     184
70     183
71     146
72     142
73     131
74      19
75      47
76     219
77      90
78     208
79     193
80     178
81     191
82      68
83     207
84      75
85     149
86     164
87      82
88      89
89     104
90      94
91     179
92       2
93       4
94      17
95      35
96     125
97     202
98      98
99      25
100     52
101    139
102     11
103    195
104     83
105     66
106     27
107    192
108    129
109    110
110    103
111    151
112    119
113    147
114    121
115    107
116    216
117    141
118    168
119    167
120     50
121     62
122     45
123    174
124     59
125    173
126    215
127    180
128    126
129    157
130    182
131     10
132    194
133    135
134    217
135    134
136    169
137    230
138     40
139     48
140     26
141    145
142    225
143     49
144     71
145    185
146    123
147    106
148     54
149      6
150    232
151     56
152    150
153    210
154    120
155    127
156      5
157    222
158    122
159    128
160     93
161    109
162     44
163     13
164     37
165     92
166    136
167    143
168    114
169    161
170     64
171      9
172     76
173    228
174    211
175    190
176    220
177    229
178    199
179    188
180    218
181    187
182     41
183     72
184    105
185    196
186    102
187    113
188    214
189    116
190    148
191    166
192     70
193     24
194     29
195     86
196     30
197     61
198     32
199    170
200     87
201    101
202     60
203     57
204     95
205     22
206     20
207    155
208    100
209    233
210    197
211    153
212     79
213     18
214    111
215    212
216    227
217     31
218     38
219     97
220     21
221      3
222    200
223    133
224     43
225    181
226    234
227     51
228     16
229    226
230    172
231     46
232     63
233     74
Name: Rank, dtype: int64

In [29]:
# Print the column names of the DataFrame to verify the correct column name
print(df2.columns)

# Once the correct column name is identified, replace 'Country' with the actual column name in the set_index method.
# For example, if the column is named 'Country Name', you would use:
# df2 = df2.set_index('Country Name')
# df2.loc['Uzbekistan']

# If you are confident that 'Country' is the correct name but there might be leading/trailing spaces,
# you can clean up the column names before setting the index.
# df2.columns = df2.columns.str.strip()
# df2 = df2.set_index('Country')
# df2.loc['Uzbekistan']

# The original code with the potentially incorrect column name:
# df2 = df2.set_index('Country') # Commenting out the problematic line

# --- INSERT THE CORRECTED CODE BELOW ---
# Based on the output of print(df2.columns), replace 'Your_Correct_Country_Column' with the actual column name
# Example:
# df2 = df2.set_index('Your_Correct_Country_Column')

# Once the index is set correctly, you can then use .loc
# df2.loc['Uzbekistan']

# If you need to strip spaces first:
# df2.columns = df2.columns.str.strip()
# df2 = df2.set_index('Your_Correct_Country_Column') # Use the potentially stripped column name
# df2.loc['Uzbekistan']

# Example based on a common column name 'Country/Territory' from similar datasets
# df2 = df2.set_index('Country/Territory')
# df2.loc['Uzbekistan']

Index(['Rank', 'CCA3', 'Capital'], dtype='object')

In [30]:
df2.iloc[224]

Rank             43
CCA3            UZB
Capital    Tashkent
Name: Uzbekistan, dtype: object